### ISSUE TITLE
Fantastic!!

### ISSUE THREAD

**Issue by jl777** [msotoodeh/curve25519#1]
this is not really an issue, but I was wondering if you had plans to vectorize your code. I think most of the code would work as a portable (probably not using ms compilers though) vectorized implementation using 
 __attribute__((ext_vector_type(4)));

but not sure how it would compare to your asm version. Of course an asm vector implementation could get ~3x the speed

Anyway, wanted to say thanks! this is quite nice implementation.

James

**Comment by msotoodeh** [comment]
Hi James,
I didn't have any plan for supporting vectorization. I also doubt if any noticeable performance gain can be achieved due to usage of seriallized big number operations. Anyway, if I get a chance, I make some experimental implementation and submit it if happy with the results.
Thanks 
Mehdi
