### ISSUE TITLE
Secret key changed first byte after public key creation

### ISSUE THREAD

**Issue by lindevs** [msotoodeh/curve25519#2]
I can't understand why after public key creation secret key first byte changed. For example:
```
unsigned char aliceSecret[32];
unsigned char alicePublic[32];

memset(aliceSecret, 'a', 32);

for (int i = 0; i < 32; i++)
{
	cout << hex << (int)aliceSecret[i] << ' ';
}
cout << endl;

curve25519_dh_CalculatePublicKey_fast(alicePublic, aliceSecret); 
	
for (int i = 0; i < 32; i++)
{
	cout << hex << (int)aliceSecret[i] << ' ';
}
```
Prints:
61 61 61 61 61 ... 61
**_60_** 61 61 61 61 ... 61

I will try another library and test if I get some result.

**Comment by msotoodeh** [comment]
This is part of the spec. Low 3 bits of first byte and high 2 bits of last byte are having fixed values.
See 'Computing secret keys' in https://cr.yp.to/ecdh.html.

**Comment by lindevs** [comment]
Thanks for information.
