### ISSUE TITLE
Comparison against curve25519-donna SSE2

### ISSUE THREAD

**Issue by matbech** [msotoodeh/curve25519#6]
I would like to see a comparison against curve25519-donna using SIMD instructions (SSE2) using the implementation from here:
https://github.com/floodyberry/curve25519-donna

Right now, the curve25519-donna portable C version is used as a comparison.

Also how does your implementation compare with:
https://github.com/armfazh/rfc7748_precomputed

**Comment by msotoodeh** [comment]
You can compare clock cycles for comparison:
DH-shared secret:
Mehdi: 43,229 cycles
armfazh: Haswell(145,800), Skylake(108,700)
floodyberry: SSE2(265K)
