### ISSUE TITLE
Mac support?

### ISSUE THREAD

**Issue by mr-pandabear** [msotoodeh/curve25519#9]
I develop on mac and it's not currently supported -- can you guide me on what needs to change to compile this library on Apple machines(x86_64-apple-darwin20.3.0) ?

**Comment by msotoodeh** [comment]
C implementation of the library is expected to be portable enough to work on mac. For best performance you can port assembly part of the library. I am not familiar with mac assembly language but it should be straight forward.

**Comment by CryptoManiac** [comment]
Both C and ASM versions are working without any issues on the latest versions of MacOS Ventura and Sonoma. You merely need to replace some headers with the standard posix ones and ensure that everything is dynamically linked.

**Comment by CryptoManiac** [comment]
I wouldn’t use the asm version though. You need to keep in mind, there are no guarantees that the apple’s Rosetta will generate a time-safe code for the x86 binaries. Better to be safe than sorry.
